### ISSUE TITLE
FindArmNoneEabiGCC.cmake has cmake syntax error when arm-none-eabi-gcc is not installed

### ISSUE THREAD

**Issue by dlandry97** [omnid/tiva-cmake#3]
CMake Error at /home/dlandry/NURE/omnids/ws/src/tiva_cmake/cmake/TivaCMake/FindArmNoneEabiGCC.cmake:84 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  lib/CMakeLists.txt:11 (find_package)

**Comment by m-elwin** [comment]
Fixed by PR #5
